[versions]
# block version
compileSdk = "36"
minSdk = "26"
targetSdk = "36"

# plugin version
agp = "8.13.2"
kotlin = "2.2.21"
ksp = "2.3.4"
hilt = "2.57.2"

# library version
gson = "2.13.2"
composeBom = "2025.12.01"
composeActivity = "1.12.2"
material = "1.4.0"
navigation = "2.9.6"
navigationHilt = "1.3.0"
room = "2.8.4"

[plugins]
com-android-application = { id = "com.android.application", version.ref = "agp" }
com-android-library = { id = "com.android.library", version.ref = "agp" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
org-jetbrains-kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
com-google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
com-google-dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

[libraries]
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

bom-compose = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "composeActivity" }

material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material" }
material3-window = { group = "androidx.compose.material3", name = "material3-window-size-class", version.ref = "material" }
navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
navigationHilt = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "navigationHilt" }

room = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

[bundles]
compose = ["compose-ui", "compose-ui-tooling", "compose-ui-util", "compose-foundation", "compose-activity",]
material = ["material3", "material3-window"]
navigation = ["navigation", "navigationHilt"]
room = ["room", "room-runtime"]